### PR TITLE
Fix a race condition when a system is started on a different queue from its event serialising queue.

### LINKED ISSUE #37: Race condition when initialising system on a queue different from its scheduler queue.
It appears that values might not be able to reach the reducer, when the system is initialised on a queue that is not the same as its scheduler queue.

### PR DESCRIPTION
**Pull request by andersio**
Resolve #37.

## Why?
Due to the nature of `prefix` lazily starting the producer being prefixed, we cannot rely on `on(value:)` to ignite the feedbacks with the initial state. At the time `prefix(value:)` calls `on(value:)` for the initial value, the events-reducer producer has not yet been started yet. Consequentially, it would lead to dropped events when the system is instantiated on a queue different from the queue used for serializing events.
         
## Explanation

The current operator application order is `prefix(value:)` followed by `on(value:)`.

Recall that `prefix(value:)` is essentially `a concat b`. Since `b` would not start before `a` completes, the `events -> reducer` part is not started until `a` has finished sending out the prefix value.

When `prefix(value:)` sends out the initial value, `on(value:)` sends the initial value to the state signal, which in turn updates all feedback signals. But since the events-reducer producer hasn’t started yet (which is the `flatMap(.concat)` semantic), all events generated by feedbacks could potentially be delivered to the void, when the queue instantiating the system runs behind the queue serialising all feedback events.

## How to fix it?

Having said that, `prefix(value:)` is guaranteed to have started the prefixed producer as part of the synchronous producer starting process. So we can address the issue by applying `on(started:)` after `prefix(value:)` to ignite the system, while having `on(value:)` applied instead before `prefix(value:)` to still keep the reducer-to-feedbacks path open.

### CODE REVIEW

**Comment by RuiAAPeres** [comment]
> Due to the nature of `prefix` lazily starting the producer being prefixed, we cannot rely on `on(value:)` to ignite the feedbacks with the initial state. At the time `prefix(value:)` calls `on(value:)` for the initial value, the events-reducer producer has not yet been started yet. Consequentially, it would lead to dropped events when the system is instantiated on a queue different from the queue used for serializing events.

I really would like to understand this fix, since we extensively use ReactiveFeedback in our codebase, but I can't even understand the first paragraph. 😢  

Do you think you could create a small diagram (like a timeline), so I can have a mental image of the events?

**Comment by andersio** [comment]
# The race condition
## Scenario A
screenshot 2019-02-28 at 23 13 00

## Scenario B
screenshot 2019-02-28 at 23 13 11

# The fix
screenshot 2019-02-28 at 23 15 45

**Comment by RuiAAPeres** [comment]
(beautiful diagrams, thanks! ❤️ )

(I am assuming S0 and S1, are related to State0 and State1?)

I am looking at scenario B, does it mean that the prefix `S0` (or initial state) is never handled by the reducer?

**Comment by andersio** [comment]
@RuiAAPeres The reducer is constructed with the `scan(initial:_:)` operator, and has been fed with the initial state directly.

The reducer wouldn’t process any state directly, only events produced by feedbacks in response to the latest state. Then by processing an event, it computes a new state that gets fed back into the feedbacks.

File: ReactiveFeedback/SignalProducer+System.swift [hunk 1]
```diff
@@ -29,8 +29,23 @@ extension SignalProducer where Error == NoError {
 
             return SignalProducer<Event, NoError>(Signal.merge(events))
                 .scan(initial, reduce)
-                .prefix(value: initial)
```
Comment (sergdort) [inline ReactiveFeedback/SignalProducer+System.swift]: Are you saying that `prefix` operator starts source producer before you even subscribe to `prefix`?

File: ReactiveFeedbackTests/SystemTests.swift [hunk 2]
```diff
@@ -181,4 +181,39 @@ class SystemTests: XCTestCase {
...
         expect(startCount) == 2
     }
+
+    func test_should_not_miss_delivery_to_reducer_when_started_asynchronously() {
+        let creationScheduler = QueueScheduler()
+        let systemScheduler = QueueScheduler()
+
+        let observedState: Atomic<[String]> = Atomic([])
+
+        let semaphore = DispatchSemaphore(value: 0)
```
Comment (RuiAAPeres) [inline ReactiveFeedbackTests/SystemTests.swift:191]: Pardon my ignorance, but why do we need the aid of semaphore for this test?

**Comment by RuiAAPeres** [comment]
~@andersio can you provide a case, in our codebase, where this bug manifests itself?~ https://github.com/Babylonpartners/babylon-ios/pull/6847

File: ReactiveFeedback/SignalProducer+System.swift (hunk 1 above)
Comment (andersio) [reply ReactiveFeedback/SignalProducer+System.swift]: No. LHS is started only after RHS (a producer emitting one value) completes, and that's the core of the issue.

File: ReactiveFeedbackTests/SystemTests.swift (hunk 2 above)
Comment (andersio) [reply ReactiveFeedbackTests/SystemTests.swift:191]: Reproducing scenarios that require specific timing order often require manual synchronisation and sometimes repeated runs to lower chance of false positives, because the OS scheduler need not do you a favour when scheduling threads, and we can only create a controlled environment at best effort with these primitives.

Alternatively, this can be done by `TestScheduler`, but only if `advance()` supports draining tasks one-by-one.

File: ReactiveFeedback/SignalProducer+System.swift (hunk 1 above)
Comment (andersio) [reply ReactiveFeedback/SignalProducer+System.swift]: RHS (the prefixed initial) sends out a value, feedbacks receive such value and produce an event, and the said event may be dequeued by the feedback loop queue before LHS (the reducer) starts on the initialising queue.

**Review by sergdort — APPROVED** [review]

File: ReactiveFeedback/SignalProducer+System.swift [hunk 3]
```diff
@@ -29,8 +29,23 @@ extension SignalProducer where Error == NoError {
...
                 .on(value: stateObserver.send(value:))
+                .prefix(value: initial)
+                .on(started: {
```
Comment (inamiy) [inline ReactiveFeedback/SignalProducer+System.swift]: TBH this doesn't look nice since `initial` is now used 3 times in this pipeline (ideally, it should only be used for "initial" setup once).

IMO the core problem is the initial feedback loop running **before system's initialization completes (regardless of which thread it had happened)**.
As this PR has just demonstrated, the reason is obviously initial (and too early) feedback passed in as an system's initializer argument, so we need to pay more attention to avoid this situation...

For now, I think it's good to have this PR accepted as a workaround.
I personally recommend to group `on(started:value:)` together so that we can recognize `on(started:)` is branched from `on(value:)`.

```swift
.on(
    started: { /* initial early feedback workaround */ }, 
    value: stateObserver.send(value:)
)
.prefix(value: initial)
```

Comment (inamiy) [reply ReactiveFeedback/SignalProducer+System.swift]: Also, we probably need to `state <~ SignalProducer.system(...).skip(first: 2)` instead since `initial` will be emitted twice.

Comment (sergdort) [reply ReactiveFeedback/SignalProducer+System.swift]: `prefix(value: initial)` sends value to observers
`stateObserver.send(value:)` sends value to `Feedbacks`

Comment (inamiy) [reply ReactiveFeedback/SignalProducer+System.swift]: @sergdort 
New pipeline shown in https://github.com/Babylonpartners/ReactiveFeedback/pull/38#discussion_r266434060 has a swapped order so `prefix(value: initial)` will no longer affect `stateObserver.send(value:)`.

Comment (sergdort) [reply ReactiveFeedback/SignalProducer+System.swift]: It will be sent there via `on(started: )`

```swift
SignalProducer<Event, NoError>(Signal.merge(events))
                .scan(initial, reduce)
                .on(value: stateObserver.send(value:))
                .prefix(value: initial)
                .on(started: {
                    // NOTE: Due to the nature of `prefix` lazily starting the producer being prefixed, we cannot rely
                    //       on `on(value:)` to ignite the feedbacks with the initial state.
                    //
                    //       At the time `prefix(value:)` calls `on(value:)` for the initial value, the events-reducer
                    //       producer has not yet been started yet. Consequentially, it would lead to dropped events
                    //       when the system is instantiated on a queue different from the queue used for
                    //       serializing events.
                    //
                    //       Having said that, `prefix(value:)` is guaranteed to have started the prefixed producer as
                    //       part of the synchronous producer starting process. So we can address the issue by applying
                    //       `on(started:)` after `prefix(value:)` to ignite the system, while having `on(value:)`
                    //       instead applied before `prefix(value:)` to keep the reducer-to-feedbacks path open.
                    stateObserver.send(value: initial)
                })
```

**Review by inamiy — CHANGES_REQUESTED** [review]
Just to not forget to fix `Property+System.swift`... https://github.com/Babylonpartners/ReactiveFeedback/pull/38#discussion_r266441485

> Also, we probably need to `state <~ SignalProducer.system(...).skip(first: 2)` instead since `initial` will be emitted twice.

**Comment by andersio** [comment]
@inamy That doesn’t sound right to me. It shouldn’t emit the initial value twice afterwards.

**Review by inamiy — APPROVED** [review]
@andersio https://github.com/Babylonpartners/ReactiveFeedback/pull/38#issuecomment-474378079
My bad. It doesn't seem required, so I will approve now 👍
